##/ ******************************* INFORMATION ***************************//
##/ ***********************************************************************//
##/
##/ ** "/common/tasks/main.yml" - Main tasks for common role
##/ ** 
##/ ** @author   Stephen McElroy <magusnebula@gmail.com>
##/ ** @date     Aug 28, 2017
##/ ** @access   public
##/ ** @type     Ansible task file
##/ ** @updated  Oct 5, 2017
##/
##/ ***********************************************************************//

---
- name: add bareos repo centos
  yum_repository: 
    name: bareos
    baseurl: http://download.bareos.org/bareos/release/{{ bareos_version }}/CentOS_7/ 
    gpgkey: http://download.bareos.org/bareos/release/{{ bareos_version }}/CentOS_7/repodata/repomd.xml.key
    description: "Bareos Repo"
    state: present
  tags:
    - repo
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: add bareos repo redhat 7
  yum_repository:
    name: bareos
    baseurl: http://download.bareos.org/bareos/release/{{ bareos_version }}/RHEL_7/
    gpgkey: http://download.bareos.org/bareos/release/{{ bareos_version }}/RHEL_7/repodata/repomd.xml.key
    description: "Bareos Repo"
    state: present
  tags:
    - repo
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "7"

- name: add bareos repo redhat 6
  yum_repository:
    name: bareos
    baseurl: http://download.bareos.org/bareos/release/{{ bareos_version }}/RHEL_6/
    gpgkey: http://download.bareos.org/bareos/release/{{ bareos_version }}/RHEL_6/repodata/repomd.xml.key
    description: "Bareos Repo"
    state: present
  tags:
    - repo
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "6"

- name: add bareos repo redhat 5
  yum_repository:
    name: bareos
    baseurl: http://download.bareos.org/bareos/release/{{ bareos_version }}/RHEL_5/
    gpgkey: http://download.bareos.org/bareos/release/{{ bareos_version }}/RHEL_5/repodata/repomd.xml.key
    description: "Bareos Repo"
    state: present
  tags:
    - repo
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "5"
